dist: bionic

language: python

cache: pip

addons:
  apt:
    packages:
      - libfuzzy-dev

python:
  - "3.6"
  - "3.6-dev"
  - "3.7"
  - "3.7-dev"
  - "3.8"
  - "3.8-dev"

install:
    - bash travis/install_travis.sh

script:
    - bash travis/test_travis.sh

after_success:
    - poetry run codecov
    - poetry run coveralls
