language: python

cache: pip

addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test' ]
    packages:
      - libstdc++6
      - libfuzzy-dev

python:
    - "2.7"
    - "3.5-dev"
    - "3.6"
    - "3.6-dev"

install:
    - pip install pipenv
    - pipenv install --dev
    - pushd tests
    - git clone https://github.com/viper-framework/viper-test-files.git
    - popd

script:
    - pipenv run nosetests --with-coverage --cover-package=pymisp,tests --cover-tests tests/test_*.py

after_success:
    - pipenv run codecov
    - pipenv run coveralls
